# Task 1 

In [110]:
# Python Program to Add Two Matrices
def Matrices_addtion(arr,brr,row1,col1):
    for i in range(row1):
        local = [0]*col1
        for j in range(col1):
            local[j] = arr[i][j]+brr[i][j]
        result.append(local)    
    return result

arr = [[1,2,3],
       [5,6,7],
       [8,15,16]]

brr = [[5 , 8, 6],
       [17,18,23],
       [25,69,89]]

row1 = len(arr)
col1 = len(arr[0])

row2 = int(len(brr))
col2 = len(brr[0])

result = []
try:
    if row1==row2 and col1==col2:
        result = Matrices_addtion(arr,brr,row1,col1)
        print("First Matrix :")
        for lst in range(len(arr)):
            print(f'{arr[lst]}')
        print()
        print("Second Matrix :")
        for lst in range(len(arr)):
            print(f'{brr[lst]}')
        print(" ")
        print("Addition of two matix is : ")

        print('[',end='')
        result_len = len(result)
        for lst in range(result_len):
            if lst !=result_len-1:
                print(f' {result[lst]} ')
            else: 
                print(f" {result[lst]}",end = ' ]')

    else:
        print("Please select proper matrix it's can'nt be added as because M1 x N1 != M2 x N2")
            
except Exception as e:
    print(e)

First Matrix :
[1, 2, 3]
[5, 6, 7]
[8, 15, 16]

Second Matrix :
[5, 8, 6]
[17, 18, 23]
[25, 69, 89]
 
Addition of two matix is : 
[ [6, 10, 9] 
 [22, 24, 30] 
 [33, 84, 105] ]

# Task 2 

# Method 1 

In [66]:
# Python Program to Multiply Two Matrices
arr = [[2, 7, 3],
       [4, 5, 6],
       [7, 8, 9]]


brr = [[5, 8, 1, 2],
       [6, 7, 3, 0],
       [4, 5, 9, 1]]

result = [[0, 0, 0, 0],
          [0, 0, 0, 0],
          [0, 0, 0, 0]]


def matrix_multiplication(A, B, result):
    try:
        for i in range(len(A)):
            for j in range(len(B[0])):
                for k in range(len(B)):
                    result[i][j] += A[i][k] * B[k][j]
        return result
    except Exception as e:
        return e


try:
    print("First Matrix :")
    for lst in range(len(arr)):
        print(f'{arr[lst]}')
    print()
    print("Second Matrix :")
    for lst in range(len(arr)):
        print(f'{brr[lst]}')
    print(" ")
    print("Multiplication of two matix is : ")

    result = matrix_multiplication(arr, brr, result)
    result_len = len(result)
    for lst in range(result_len):
        print(f'{result[lst]}')

except Exception as e:
    print(e)


First Matrix :
[2, 7, 3]
[4, 5, 6]
[7, 8, 9]

Second Matrix :
[5, 8, 1, 2]
[6, 7, 3, 0]
[4, 5, 9, 1]
 
Multiplication of two matix is : 
[64, 80, 50, 7]
[74, 97, 73, 14]
[119, 157, 112, 23]


# Method 2 

In [67]:
# Python Program to Multiply Two Matrices
def matrix_multiplication_2(arr,brr):
    try:
        return np.dot(arr,brr)
    except Exception as e:
        return e
    

try:
    print("First Matrix :")
    for lst in range(len(arr)):
        print(f'{arr[lst]}')
    print()
    print("Second Matrix :")
    for lst in range(len(arr)):
        print(f'{brr[lst]}')
    print(" ")
    print("Multiplication of two matix is : ")

    result = matrix_multiplication_2(arr, brr)
    result_len = len(result)
    for lst in range(result_len):
        print(f'{result[lst]}')

except Exception as e:
    print(e)

First Matrix :
[2, 7, 3]
[4, 5, 6]
[7, 8, 9]

Second Matrix :
[5, 8, 1, 2]
[6, 7, 3, 0]
[4, 5, 9, 1]
 
Multiplication of two matix is : 
[64 80 50  7]
[74 97 73 14]
[119 157 112  23]


# Task 3 

In [83]:
# Python Program to Transpose a Matrix
    
arr = [[12,7],
    [4 ,5],
    [3 ,8]]

def transpoce(arr):
    try:
        result =  []
        for i in range(len(arr[0])):
            local = [0]*len(arr)
            for j in range(len(arr)):   
                local[j] = arr[j][i]
            result.append(local)
        return result
    except Exception as e:
        return e
    
try: 
    print("Matric : ")
    for lst in arr:
        print(f'    {lst} ')
    print(' ')
    print("Matrix after Transpose : " )
    result = transpoce(arr)
    for lst in result:
        print(f'    {lst} ')
    print(' ')
    
except Exception as e:
    print(e)

Matric : 
    [12, 7] 
    [4, 5] 
    [3, 8] 
 
Matrix after Transpose : 
    [12, 4, 3] 
    [7, 5, 8] 
 


# Task 4 

In [109]:
# Python Program to Sort Words in Alphabetic Order
def string_sort(string):
    try:
        a = sorted(string)
        a = ''.join(a)
        return a
    except Exception as e:
        return e
    
try:
    string = input("Enter string which need to sort : ")
    print(f"The Normal string : \033[1m{string}\033[0m and \nSorted string : \033[1m{string_sort(string)} ")
    
except Exception as e:
    print(e)

Enter string which need to sort : jaiswal
The Normal string : jaiswal and 
Sorted string : aaijlsw 


# Task 5

In [106]:
# Python Program to Remove Punctuation From a String
import re
def remove_punch(string):
    try:
        patten = '[a-zA-Z1-8 ]'
        form = ''
        for word in string:
            if re.search(patten,word):
                form+=word
        return form
    except Exception as e:
        return e      
    
try:
    string = input("Enter Name to remove Punctuation : ")
    print('-'*50)
    print(f"The Normal string : \033[1m{string}\033[0m and \nPunctuation remove string : \033[1m{remove_punch(string)} ")
    
except Exception as e:
    print(e)

Enter Name to remove Punctuation : Alway? help& each_ other
--------------------------------------------------
The Normal string : Alway? help& each_ other and 
Punctuation remove string : Alway help each other 


In [97]:
print("\u2764\ufe0f Thank you i-Neuron Team ...! \u2764\ufe0f")

❤️ Thank you i-Neuron Team ...! ❤️
